# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nomeinformado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pesquisa', models.DateField()),
                ('data', models.DateField()),
                ('temperatura', models.IntegerField()),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templogger.Cidade')),
            ],
        ),
    ]
